import{a as b,S as w,i as u}from"./assets/vendor-b2578120.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function p(t,o){const r="https://pixabay.com/api/",i=new URLSearchParams({key:"43019776-35548046cc937008d4e9556be",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o});try{return(await b.get(r,{params:i})).data}catch{console.log("error")}}const c=document.querySelector(".gallery");function f(t){if(t.length==0)u.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",width:"432px",height:"88px"});else{const o=t.map(r=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img
        loading="lazy"
        class="photo"
        src="${r.webformatURL}" 
        alt="${r.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");c.insertAdjacentHTML("beforeend",o),S.refresh()}}const S=new w(".photos-list-link",{captionsData:"alt",captionDelay:250}),d=document.querySelector(".form"),g=document.querySelector(".loader"),h=document.querySelector(".btn-load");let n,a,m=0;const v=15;d.addEventListener("submit",P);async function P(t){t.preventDefault(),y(),n=d.elements.searchQuery.value.trim().toLowerCase(),a=1;try{const o=await p(n,a);m=Math.ceil(o.totalHits/v),n===""?(c.innerHTML="",u.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",width:"432px",height:"88px"})):(c.innerHTML="",f(o.hits),F()),d.reset()}catch{console.log("error")}L()}h.addEventListener("click",x);async function x(){a+=1,y();try{const t=await p(n,a);f(t.hits),M(),F(),a>=m&&u.info({message:"We're sorry, but you've reached the end of search results",color:"blue",position:"topRight",theme:"light",progressBarColor:"#FFFFFF"})}catch{console.log("error")}L()}function M(){const t=c.firstChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function y(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function q(){h.classList.remove("hidden")}function C(){h.classList.add("hidden")}function F(){a>=m?C():q()}
//# sourceMappingURL=commonHelpers.js.map
