import{a as F,S,i as m}from"./assets/vendor-b2578120.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function p(o,t){const r="https://pixabay.com/api/",a=new URLSearchParams({key:"43019776-35548046cc937008d4e9556be",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});try{return(await F.get(r,{params:a})).data}catch(e){console.error(e)}}const c=document.querySelector(".gallery");function h(o){const t=o.map(r=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img
        loading="lazy"
        class="photo"
        src="${r.webformatURL}" 
        alt="${r.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");c.insertAdjacentHTML("beforeend",t),v.refresh()}const v=new S(".photos-list-link",{captionsData:"alt",captionDelay:250}),d=document.querySelector(".form"),f=document.querySelector(".loader"),u=document.querySelector(".btn-load");let i,n,g=0;const M=15;d.addEventListener("submit",P);async function P(o){o.preventDefault(),y(),i=d.elements.searchQuery.value.trim().toLowerCase(),n=1;try{const t=await p(i,n);g=Math.ceil(t.totalHits/M),t.hits.length===0||i===""?(c.innerHTML="",m.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",width:"432px",height:"88px"}),b()):(c.innerHTML="",h(t.hits),w()),d.reset()}catch(t){console.error(t)}L()}u.addEventListener("click",q);async function q(){n+=1,y();try{const o=await p(i,n);h(o.hits),x(),w()}catch(o){console.error(o)}L()}function x(){const o=c.firstChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}function y(){f.classList.remove("hidden")}function L(){f.classList.add("hidden")}function C(){u.classList.remove("hidden")}function b(){u.classList.add("hidden")}function w(){n>=g?(b(),m.info({message:"We're sorry, but you've reached the end of search results",color:"blue",position:"topRight",theme:"light",progressBarColor:"#FFFFFF"})):C()}
//# sourceMappingURL=commonHelpers.js.map
